version: '3'

services:
  server:
    image: node:12.13
    restart: always
    working_dir: /srv/node
    volumes:
      - .:/srv/node:rw,cached
    ports:
      - 3000:3000
    command: /bin/sh -c 'npm install && npm run build && npm run watch'
  
